---
title: "workflowr_configuration"
author: "Nel Marín"
date: "18/4/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/Nel/Documents/IrsiCaixa/PROYECTOS/firstproject")
```

## Configuration of workflowr

```{r}

#install.packages("installr")
#library(installr)
#updateR()

#install.packages("git2r")
#install.packages("workflowr")
#library(workflowr)

#Configure Git (only need to do once per computer)
#wflow_git_config()
#wflow_git_config(user.name = "Nel Marin", user.email = "nmarin@irsicaixa.es")

#Start my first workflowr project
#wflow_start("firstproject")

#Build the website
#wflow_build()

#View the website (docs/index.html) on my local machine
#wflow_view()

#View the status of teh workflowr project
#wflow_status()

#Publish the project files
#wflow_publish(c("analysis/index.Rmd", "analysis/about.Rmd", "analysis/license.Rmd"), "Publish the initial files for firstproject")

#Put the code on GitHub as an online website
#wflow_use_github("nmarin-irsi")

#Send/push the files to GitHub
#wflow_git_push() did not work
#In GitBash, I used teh command "git push -u origin master" in the project folder

```
